define(function(require) {    
    require('css!assets/css/main');    
    var zagame = require('./game');
    zagame.init(
        [
            {
                "name":"ball",
                "svg":require('text!assets/svg/ball.svg'),
            },
            {
                "name":"player1",
                "svg":require('text!assets/svg/player1.svg')
            },
            {
                "name":"player2",
                "svg":require('text!assets/svg/player2.svg')
            },
            {
                "name":"blue1",
                "svg":require('text!assets/svg/brick.svg')
            },
            {
                "name":"red1",
                "svg":require('text!assets/svg/brick.svg')
            },
            {
                "name":"green1",
                "svg":require('text!assets/svg/brick.svg')
            },
            {
                "name":"yellow1",
                "svg":require('text!assets/svg/brick.svg')
            },
            {
                "name":"silver1",
                "svg":require('text!assets/svg/brick.svg')
            },
            {
                "name":"purple1",
                "svg":require('text!assets/svg/brick.svg')
            },            
        ]
    );
});